### ISSUE TITLE
Diverse Errors

### ISSUE THREAD

**Issue by jh537** [torbennehmer/hacs-e3dc#201]
### System Health details

cannot be found

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

No direct problems but error messages

get_batteries_data | 

EMS_REQ_GET_MANUAL_CHARGE |  

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
get_batteries_data | 

EMS_REQ_GET_MANUAL_CHARGE |
```

[config_entry-e3dc_rscp-01JCDQ4QM22GY7HNBQB5D92WRM.4.json](https://github.com/user-attachments/files/17791732/config_entry-e3dc_rscp-01JCDQ4QM22GY7HNBQB5D92WRM.4.json)

**Comment by jh537** [comment]
[config_entry-e3dc_rscp-01JCDQ4QM22GY7HNBQB5D92WRM(4).json](https://github.com/user-attachments/files/17791730/config_entry-e3dc_rscp-01JCDQ4QM22GY7HNBQB5D92WRM.4.json)

**Comment by torbennehmer** [comment]
@jh537 Thank you

The problem in EMS_REQ_GET_MANUAL_CHARGE is a known bug in pye3dc, I'm waiting for a new upstream release, which will fix this. See #114, you'll find the error described there.

I have no idea, what your get_batteries_data is doing though. Looks as if no temperatures are being reported by your unit. Unfortunately, this too is an upstream pye3dc topic, it can't be fixed in this repository. Im calling directly into the pye3dc method `get_batteries_data`, which then bails. Please file the bug in the other repository, ideally with a minimal command line example (he's not working on my HACS extension).

Thanks!

**Comment by torbennehmer** [comment]
@jh537 PS: The failing get_batteries_data call is currently not affecting the normal integration operation. I'm querying the batteries in the diagnostic dump to get a complete picture of the E3DC unit in question. So, right now, this is a purely diagnostic data. This will change in the future, as we will get data like SOH of the batteries at some point. No timeline there yet, though.
